#feat Новый функционал
armustafin/java-shareit pull request #1
Opened 2023-08-17 16:35 UTC by armustafin

2023-08-18 17:44 UTC, kalitva requested changes

2023-08-18 17:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>   */
Поудаляй эти комменты

2023-08-18 17:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/repository/ItemStorageIml.java
> +        } else {
Нам точно нужен этот else?

2023-08-18 17:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private final UserServiceIml userService;
Храни сервис по типу интерфейса
`UserServiceIml --> UserService`

2023-08-18 17:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +@Data
Давай вместо `@Data` использовать 
```java
@Getter
@Setter
```

2023-08-18 17:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/repository/UserStorageIml.java
> +@Validated
Надо валидировать в контоллерах не в стораджах

2023-08-18 17:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/repository/UserStorageIml.java
> +    private final HashMap<Integer, User> users;
По типу интерфейса `HashMap --> Map`

2023-08-18 17:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/UserServiceIml.java
> +        }
```java
        if (nameDto != null && !nameDto.isEmpty()) {
                user.setName(userDto.getName());
        }
```

2023-08-18 17:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/UserServiceIml.java
> +        if (user != null) {
Инвертируй условие и избавься от `else`

2023-08-19 19:08 UTC, kalitva requested changes

2023-08-19 19:08 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
Лучше избегай статических методов, инжекти мапперы спрингом

2023-08-19 19:08 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@Data
```java
@Getter
@Setter
```

2023-08-19 19:08 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/repository/ItemStorageIml.java
> +@Validated
Нам нужна эта аннотация?

2023-08-19 19:08 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceIml.java
> +        if (item.getOwner().getId() == userId) {
Инвертируй это условие, затем избавься от `else`

2023-08-19 19:08 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/repository/UserStorageIml.java
> +    public User update(@Valid @RequestBody User user, Integer id) {
Мы же говорили по поводу валидаций в сторадже... И зачем здесь `@RequestBody`?

2023-08-20 05:55 UTC, armustafin commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
статистический метод был в рекомендациях

2023-08-20 15:20 UTC, kalitva approved these changes

2023-08-20 15:20 UTC, kalitva commented on pom.xml
> -				<plugin>
Это нельзя удалять, в следующем эти плагины будут задействованы в CI/CD

2023-08-20 15:20 UTC, kalitva commented on src/main/java/ru/practicum/shareit/exception/ExceptionHandler.java
> +    }
Пожалуйста, логируй во всех обработчиках

2023-08-20 15:20 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/UserServiceIml.java
> +            if (!emailDto.isEmpty()) {
Здесь же аналогичный кейс, как в замечании выше, пожалуйста внимательно

2023-08-21 17:19 UTC, merged