#feat Тесты и новая функциональность
armustafin/java-shareit pull request #3
Opened 2023-09-24 20:05 UTC by armustafin

2023-09-26 16:28 UTC, kalitva requested changes

2023-09-26 16:28 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>      @RequestMapping(method = RequestMethod.GET)
`@RequestMapping(method = RequestMethod.GET) --> @GetMapping`

2023-09-26 16:28 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                      @RequestParam(value = "state", defaultValue = "ALL") String state,
Передавать `value` в `@RequestParam` необязательно если имя параметра урл совпадает с именем парметра метода

2023-09-26 16:28 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<Booking> getAllByUser(int userId, String state, int from, int size);
Давай в сервисе принимать сразу `Pageable` вместо `from` и `size`

2023-09-26 16:28 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceDao.java
> +        if (from < 0) {
Давай параметры пагинации проверять с помощью java-bean-validation аннотаций, поставив их прямо перед параметрами методов контроллеров

https://www.baeldung.com/spring-validate-requestparam-pathvariable

2023-09-26 16:28 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +@Table(name = "itemrequest")
`itemrequest --> item_request`

2023-09-27 18:15 UTC, kalitva requested changes

2023-09-27 18:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                             @RequestParam(required = false,
Если есть `defaultValue`, `required` автоматически выставляется в `false`, нет необходимости указывать явно

2023-09-27 18:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>      @PostMapping()
`@PostMapping` Пожалуйста без лишних скбочек

2023-09-27 18:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public Item getItem(ItemDto itemDto, Item item, ItemRequest ir) {
`ir --> itemRequest` Параметры методов лучше не сокращай

2023-09-27 18:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>  import javax.persistence.*;
Не используй wildcard импорты

2023-09-27 18:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +@Table(name = "itemrequest")
Почему замечание проигнорировано? По конвенции слова для названий таблиц и полей БД разделяются нижним подчеркиванием (бдшки как правило case insesitive по дефолту)

Проверь `schema.sql` чтобы все названия таблиц через были через underscore

2023-09-28 19:28 UTC, kalitva approved these changes

2023-09-28 19:28 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<Booking> getAllByUser(int userId, String state, PageRequest pageRequest);
`PageRequest --> Pageable` Давай расширим параметр до интерфейса

2023-09-28 19:28 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>      @PostMapping()
Почему ты помечаешь комментарий как resolved не выполнив его?

2023-09-28 19:28 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/RequestMapper.java
> +    public ItemRequestInfo maptoInfoDto(ItemRequest ir, List<ItemDto> items) {
`ir --> ItemRequest` Я кажется уже делал подобное замечание...

2023-09-28 19:28 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/User.java
>  import javax.persistence.*;
Не используй wildcard

2023-09-28 19:28 UTC, kalitva commented on src/main/resources/shema.sql
> +    CONSTRAINT fk_items_to_request FOREIGN KEY (request_id) REFERENCES Item_request (id)
`Item_request --> item_request`

2023-09-29 17:04 UTC, armustafin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>      @PostMapping()
Странно у меня в ItemController
  @GetMapping
    public List<ItemInfoDto> getAllByItem(@RequestHeader("X-Sharer-User-Id") int userId) {
        return itemService.getAllByItem(userId);
    }

2023-09-29 17:10 UTC, armustafin commented on src/main/resources/shema.sql
> +    CONSTRAINT fk_items_to_request FOREIGN KEY (request_id) REFERENCES Item_request (id)
Вроде поставил в коде стайл ограничение 50 ).... Надеюсь больше не повториться

2023-09-29 17:10 UTC, armustafin commented on src/main/java/ru/practicum/shareit/user/User.java
>  import javax.persistence.*;
Вроде поставил в коде стайл ограничение 50 ).... Надеюсь больше не повториться

2023-09-29 19:21 UTC, merged