#feat docker
armustafin/java-shareit pull request #4
Opened 2023-10-04 18:11 UTC by armustafin

2023-10-06 06:43 UTC, kalitva requested changes

2023-10-06 06:43 UTC, kalitva commented on docker-compose.yml
> +    image: gateway
`image` не нужен, мы же собираем из докерфайла

2023-10-06 06:43 UTC, kalitva commented on docker-compose.yml
> +    image: server
То же самое

2023-10-06 06:43 UTC, kalitva commented on docker-compose.yml
> +
Лишние пустые линии

2023-10-06 06:43 UTC, kalitva commented on gateway/pom.xml
> +            <artifactId>httpclient</artifactId>
Зачем нам `httpClient`?

2023-10-06 06:43 UTC, kalitva commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +
Лишние пустые линии

2023-10-06 06:43 UTC, kalitva commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/IntervalConstraint.java
> +
Пустые линии

2023-10-06 06:43 UTC, kalitva commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/IntervalValidator.java
> +        log.info("Validate");
Бесполезное сообщение, давай удалим его

2023-10-06 06:43 UTC, kalitva commented on server/src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +    List<Comment> findCommentsByItem_IdOrderByCreated(Integer id);
`findCommentsByItemIdOrderByCreated`

2023-10-06 06:43 UTC, kalitva commented on server/src/main/java/ru/practicum/shareit/user/repository/UserStorage.java
> +    User add(@RequestBody User user);
Нам точно нужны эти аннотации `@RequestBody `?

2023-10-06 06:43 UTC, kalitva commented on server/src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingService bookingService;
private

2023-10-06 15:45 UTC, armustafin commented
<dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            Была в поме примера который рекомендовали в тз а при отстуствие зависимости в гите не запускается приложение

2023-10-07 06:39 UTC, kalitva approved these changes

2023-10-07 06:39 UTC, kalitva commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/StatusDto.java
> +public enum StatusDto {
Почему dto? Это же энам... И уточни в названии чей статус

2023-10-07 06:39 UTC, kalitva commented on server/src/main/java/ru/practicum/shareit/booking/Status.java
> +public enum Status {
Чей статус? Уточни в названии

2023-10-10 16:30 UTC, merged